[package]
name = "dlib_wrappers"
version = "0.1.0"
edition = "2024"

build = "build.rs"

[dependencies]
cpp = "0.5.4"
image = "0.23.4"

[build-dependencies]
cpp_build = "0.5.4"
pkg-config = "0.3.32"

